### ISSUE TITLE
posso utilizar seu projeto aqui?

### ISSUE THREAD

**Issue by ghost** [bresantos/JAVA-Part2#1]

**Comment by bresantos** [comment]
Olá, não há licença no meu código e não vejo problemas em você se basear nele para a criação do seu jogo. ficarei feliz com a referenciação obrigada!

**Comment by lucasnuic** [comment]
Oi @bresantos, obrigado pela permissão de me basear no seu jogo. mas mesmo assim, por favor adicione uma licença nele.  o jogo que estou criando é esse: https://github.com/lucasnuic/wubbalubba  - é um jogo da memória feito em php, js e java. php é a versão webserver, js é a versão client e java é a versão desktop.
